INSERT INTO ROLE(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('true','true','ADMON');
INSERT INTO ROLE(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('true','true','CONSULTA');
INSERT INTO ROLE(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('true','true','DESARROLLADOR');

INSERT INTO USER (BLOCKED,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID) VALUES ('true','gmendoza@gmail.com','Geovanny','Mendoza','123',1);
INSERT INTO USER (BLOCKED,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID) VALUES ('true','kaguirre@gmail.com','Ketty','Aguirre','123',3);
INSERT INTO USER (BLOCKED,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID) VALUES ('true','mmendoza@gmail.com','Matias','Mendoza','223',1);

INSERT INTO USER_ROLES (USER_ID,ROLES_ID) VALUES(1,1);
INSERT INTO USER_ROLES (USER_ID,ROLES_ID) VALUES(2,1);
INSERT INTO USER_ROLES (USER_ID,ROLES_ID) VALUES(3,3);