INSERT INTO ROLES(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('TRUE','TRUE','Admon');
INSERT INTO ROLES(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('TRUE','FALSE','Consulta');
INSERT INTO ROLES(ACCESS_MODULE2, MODULE1AUTHORIZED,NAME) VALUES('FALSE','TRUE','Desarrollador');

INSERT INTO USERS(BLOCKED,CONTACT_EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID_ROLE,COUNTRY) VALUES ('FALSE','gmendoza@gmail.com','Geovanny','Mendoza','123',1,'Colombia');
INSERT INTO USERS(BLOCKED,CONTACT_EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID_ROLE,COUNTRY) VALUES ('FALSE','kaguirre@gmail.com','Ketty','Aguirre','123',3,'Mexico');
INSERT INTO USERS(BLOCKED,CONTACT_EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,MAIN_ROLE_ID_ROLE,COUNTRY) VALUES ('TRUE','mmendoza@gmail.com','Matias','Mendoza','223',1,'Nicaragua');

INSERT INTO USERS_ROLES (USER_ID_USER,ROLES_ID_ROLE) VALUES(1,1);
INSERT INTO USERS_ROLES (USER_ID_USER,ROLES_ID_ROLE) VALUES(2,1);
INSERT INTO USERS_ROLES (USER_ID_USER,ROLES_ID_ROLE) VALUES(3,3);